apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zipkin.fullname" . }}
  namespace: {{ .Values.global.namespace | default "petclinic" }}
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zipkin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zipkin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: zipkin
          image: {{ include "zipkin.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9411
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
