global:
  imageRegistry: "268015775379.dkr.ecr.us-east-1.amazonaws.com"
  imageTag: "v1.0.34"
  namespace: production
  springProfile: docker
  configServerUrl: "http://config-server:8888"
  eurekaDefaultZone: "http://discovery-server:8761/eureka/"
api-gateway:
  service:
    type: LoadBalancer
    port: 80
    acmCertificateArn: "arn:aws:acm:us-east-1:268015775379:certificate/0b3c1b3a-df26-4c95-b4fb-d85f613fc4e5"
  replicaCount: 2
genai-service:
  replicaCount: 1
  genaiSecret:
    openaiApiKey: "CHANGE_ME"
    azureOpenaiKey: ""
    azureOpenaiEndpoint: ""
config-server:
  replicaCount: 2
discovery-server:
  replicaCount: 2
customers-service:
  replicaCount: 2
vets-service:
  replicaCount: 2
visits-service:
  replicaCount: 2
admin-server:
  replicaCount: 1
zipkin:
  replicaCount: 1
prometheus:
  replicaCount: 1
grafana:
  replicaCount: 1
