replicaCount: 1

image:
  repository: "grafana/grafana"
  tag: "11.3.0"
  pullPolicy: IfNotPresent

adminPassword: "petclinic"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    memory: 256Mi
    cpu: 300m
  requests:
    memory: 128Mi
    cpu: 100m
